import { startWith } from "rxjs";
import ROUTES from "./Routes";

const COUNTRIES = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas (the)",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia (Plurinational State of)",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory (the)",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  KY: "Cayman Islands (the)",
  CF: "Central African Republic (the)",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands (the)",
  CO: "Colombia",
  KM: "Comoros (the)",
  CD: "Congo (the Democratic Republic of the)",
  CG: "Congo (the)",
  CK: "Cook Islands (the)",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czechia",
  CI: "Côte d'Ivoire",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic (the)",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands (the) [Malvinas]",
  FO: "Faroe Islands (the)",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories (the)",
  GA: "Gabon",
  GM: "Gambia (the)",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Holy See (the)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran (Islamic Republic of)",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "Korea (the Democratic People's Republic of)",
  KR: "Korea (the Republic of)",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic (the)",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands (the)",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia (Federated States of)",
  MD: "Moldova (the Republic of)",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands (the)",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger (the)",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands (the)",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine, State of",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines (the)",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  MK: "Republic of North Macedonia",
  RO: "Romania",
  RU: "Russian Federation (the)",
  RW: "Rwanda",
  RE: "Réunion",
  BL: "Saint Barthélemy",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin (French part)",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten (Dutch part)",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan (the)",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic of",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands (the)",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates (the)",
  GB: "United Kingdom of Great Britain and Northern Ireland (the)",
  UM: "United States Minor Outlying Islands (the)",
  US: "United States of America (the)",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela (Bolivarian Republic of)",
  VN: "Vietnam",
  VG: "Virgin Islands (British)",
  VI: "Virgin Islands (U.S.)",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  AX: "Åland Islands",
};

//get todday
const today = new Date();
const dd = String(today.getDate()).padStart(2, "0");
const mm = String(today.getMonth() + 1).padStart(2, "0"); //January is 0!
const yyyy = today.getFullYear();
const TODAYDATE = yyyy + "-" + mm + "-" + dd;

const COMPANYTYPE = [
  "SOLE_TRADER",
  "BRANCH_OF_FOREIGN_COMPANY",
  "SAOC",
  "LLC",
  "HOLDING_COMPANY",
  "CPV",
  "GENERAL_PARTNERSHIP",
  "LIMITED_PARTNERSHIP",
  "GOVERNMENT_OR_STATE",
  "OTHER",
];

const SECTOR = [
  "AGRICULTURE_FISHERY",
  "ARTS_ENTERTAINMENT",
  "CONSTRUCTION_INFRASTRUCTURE",
  "GOODS_RETAIL",
  "EDTECH_EDUCATION",
  "ENERGY",
  "FASHION_DESIGN",
  "FINTECH_FINANCE",
  "FOODTECH_FOOD_BEVERAGE",
  "HEALTH_WELLNESS",
  "HEALTHCARE",
  "IT",
  "MANUFACTURING",
  "SERVICE",
  "SPORT",
  "TRANSPORT",
  "REAL_ESTATE",
  "SCIENCE_RESEARCH_DEVELOPMENT",
  "TRAVEL_TOURISM",
  "OTHER",
];


const handlePhoneInput = (e) => {
  if (e) return true
  else return false
}

const CURRENCY = ["USD", "OMR", "AED", "SAR", "QAR", "BHD", "KWD"];

const arrayOfCountries = [
  {
    name: "Afghanistan",
    dial_code: "93",
    code: "AF",
    digitCount: "2",
  },
  {
    name: "Aland Islands",
    dial_code: "358",
    code: "AX",
    digitCount: "3",
  },
  {
    name: "Albania",
    dial_code: "355",
    code: "AL",
    digitCount: "3",
  },
  {
    name: "Algeria",
    dial_code: "213",
    code: "DZ",
    digitCount: "3",
  },
  {
    name: "AmericanSamoa",
    dial_code: "1684",
    code: "AS",
    digitCount: "4",
  },
  {
    name: "Andorra",
    dial_code: "376",
    code: "AD",
    digitCount: "3",
  },
  {
    name: "Angola",
    dial_code: "244",
    code: "AO",
    digitCount: "3",
  },
  {
    name: "Anguilla",
    dial_code: "1264",
    code: "AI",
    digitCount: "4",
  },
  {
    name: "Antarctica",
    dial_code: "672",
    code: "AQ",
    digitCount: "3",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "1268",
    code: "AG",
    digitCount: "4",
  },
  {
    name: "Argentina",
    dial_code: "54",
    code: "AR",
    digitCount: "2",
  },
  {
    name: "Armenia",
    dial_code: "374",
    code: "AM",
    digitCount: "3",
  },
  {
    name: "Aruba",
    dial_code: "297",
    code: "AW",
    digitCount: "3",
  },
  {
    name: "Australia",
    dial_code: "61",
    code: "AU",
    digitCount: "2",
  },
  {
    name: "Austria",
    dial_code: "43",
    code: "AT",
    digitCount: "2",
  },
  {
    name: "Azerbaijan",
    dial_code: "994",
    code: "AZ",
    digitCount: "3",
  },
  {
    name: "Bahamas",
    dial_code: "1242",
    code: "BS",
    digitCount: "4",
  },
  {
    name: "Bahrain",
    dial_code: "973",
    code: "BH",
    digitCount: "3",
  },
  {
    name: "Bangladesh",
    dial_code: "880",
    code: "BD",
    digitCount: "3",
  },
  {
    name: "Barbados",
    dial_code: "1246",
    code: "BB",
    digitCount: "3",
  },
  {
    name: "Belarus",
    dial_code: "375",
    code: "BY",
    digitCount: "3",
  },
  {
    name: "Belgium",
    dial_code: "32",
    code: "BE",
    digitCount: "2",
  },
  {
    name: "Belize",
    dial_code: "501",
    code: "BZ",
    digitCount: "3",
  },
  {
    name: "Benin",
    dial_code: "229",
    code: "BJ",
    digitCount: "3",
  },
  {
    name: "Bermuda",
    dial_code: "1441",
    code: "BM",
    digitCount: "4",
  },
  {
    name: "Bhutan",
    dial_code: "975",
    code: "BT",
    digitCount: "3",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "591",
    code: "BO",
    digitCount: "3",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "387",
    code: "BA",
    digitCount: "3",
  },
  {
    name: "Botswana",
    dial_code: "267",
    code: "BW",
    digitCount: "3",
  },
  {
    name: "Brazil",
    dial_code: "55",
    code: "BR",
    digitCount: "2",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "246",
    code: "IO",
    digitCount: "3",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "673",
    code: "BN",
    digitCount: "3",
  },
  {
    name: "Bulgaria",
    dial_code: "359",
    code: "BG",
    digitCount: "3",
  },
  {
    name: "Burkina Faso",
    dial_code: "226",
    code: "BF",
    digitCount: "3",
  },
  {
    name: "Burundi",
    dial_code: "257",
    code: "BI",
    digitCount: "3",
  },
  {
    name: "Cambodia",
    dial_code: "855",
    code: "KH",
    digitCount: "3",
  },
  {
    name: "Cameroon",
    dial_code: "237",
    code: "CM",
    digitCount: "3",
  },
  {
    name: "Canada",
    dial_code: "1",
    code: "CA",
    digitCount: "1",
  },
  {
    name: "Cape Verde",
    dial_code: "238",
    code: "CV",
    digitCount: "3",
  },
  {
    name: "Cayman Islands",
    dial_code: "345",
    code: "KY",
    digitCount: "3",
  },
  {
    name: "Central African Republic",
    dial_code: "236",
    code: "CF",
    digitCount: "3",
  },
  {
    name: "Chad",
    dial_code: "235",
    code: "TD",
    digitCount: "3",
  },
  {
    name: "Chile",
    dial_code: "56",
    code: "CL",
    digitCount: "2",
  },
  {
    name: "China",
    dial_code: "86",
    code: "CN",
    digitCount: "2",
  },
  {
    name: "Christmas Island",
    dial_code: "61",
    code: "CX",
    digitCount: "2",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "61",
    code: "CC",
    digitCount: "2",
  },
  {
    name: "Colombia",
    dial_code: "57",
    code: "CO",
    digitCount: "2",
  },
  {
    name: "Comoros",
    dial_code: "269",
    code: "KM",
    digitCount: "3",
  },
  {
    name: "Congo",
    dial_code: "242",
    code: "CG",
    digitCount: "3",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "243",
    code: "CD",
    digitCount: "3",
  },
  {
    name: "Cook Islands",
    dial_code: "682",
    code: "CK",
    digitCount: "3",
  },
  {
    name: "Costa Rica",
    dial_code: "506",
    code: "CR",
    digitCount: "3",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "225",
    code: "CI",
    digitCount: "3",
  },
  {
    name: "Croatia",
    dial_code: "385",
    code: "HR",
    digitCount: "3",
  },
  {
    name: "Cuba",
    dial_code: "53",
    code: "CU",
    digitCount: "2",
  },
  {
    name: "Cyprus",
    dial_code: "357",
    code: "CY",
    digitCount: "3",
  },
  {
    name: "Czech Republic",
    dial_code: "420",
    code: "CZ",
    digitCount: "3",
  },
  {
    name: "Denmark",
    dial_code: "45",
    code: "DK",
    digitCount: "2",
  },
  {
    name: "Djibouti",
    dial_code: "253",
    code: "DJ",
    digitCount: "3",
  },
  {
    name: "Dominica",
    dial_code: "1767",
    code: "DM",
    digitCount: "4",
  },
  {
    name: "Dominican Republic",
    dial_code: "1849",
    code: "DO",
    digitCount: "4",
  },
  {
    name: "Ecuador",
    dial_code: "593",
    code: "EC",
    digitCount: "3",
  },
  {
    name: "Egypt",
    dial_code: "20",
    code: "EG",
    digitCount: "2",
  },
  {
    name: "El Salvador",
    dial_code: "503",
    code: "SV",
    digitCount: "3",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "240",
    code: "GQ",
    digitCount: "3",
  },
  {
    name: "Eritrea",
    dial_code: "291",
    code: "ER",
    digitCount: "3",
  },
  {
    name: "Estonia",
    dial_code: "372",
    code: "EE",
    digitCount: "3",
  },
  {
    name: "Ethiopia",
    dial_code: "251",
    code: "ET",
    digitCount: "3",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "500",
    code: "FK",
    digitCount: "3",
  },
  {
    name: "Faroe Islands",
    dial_code: "298",
    code: "FO",
    digitCount: "3",
  },
  {
    name: "Fiji",
    dial_code: "679",
    code: "FJ",
    digitCount: "3",
  },
  {
    name: "Finland",
    dial_code: "358",
    code: "FI",
    digitCount: "3",
  },
  {
    name: "France",
    dial_code: "33",
    code: "FR",
    digitCount: "2",
  },
  {
    name: "French Guiana",
    dial_code: "594",
    code: "GF",
    digitCount: "3",
  },
  {
    name: "French Polynesia",
    dial_code: "689",
    code: "PF",
    digitCount: "3",
  },
  {
    name: "Gabon",
    dial_code: "241",
    code: "GA",
    digitCount: "3",
  },
  {
    name: "Gambia",
    dial_code: "220",
    code: "GM",
    digitCount: "3",
  },
  {
    name: "Georgia",
    dial_code: "995",
    code: "GE",
    digitCount: "3",
  },
  {
    name: "Germany",
    dial_code: "49",
    code: "DE",
    digitCount: "2",
  },
  {
    name: "Ghana",
    dial_code: "233",
    code: "GH",
    digitCount: "3",
  },
  {
    name: "Gibraltar",
    dial_code: "350",
    code: "GI",
    digitCount: "3",
  },
  {
    name: "Greece",
    dial_code: "30",
    code: "GR",
    digitCount: "2",
  },
  {
    name: "Greenland",
    dial_code: "299",
    code: "GL",
    digitCount: "3",
  },
  {
    name: "Grenada",
    dial_code: "1473",
    code: "GD",
    digitCount: "4",
  },
  {
    name: "Guadeloupe",
    dial_code: "590",
    code: "GP",
    digitCount: "3",
  },
  {
    name: "Guam",
    dial_code: "1671",
    code: "GU",
    digitCount: "4",
  },
  {
    name: "Guatemala",
    dial_code: "502",
    code: "GT",
    digitCount: "3",
  },
  {
    name: "Guernsey",
    dial_code: "44",
    code: "GG",
    digitCount: "2",
  },
  {
    name: "Guinea",
    dial_code: "224",
    code: "GN",
    digitCount: "3",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "245",
    code: "GW",
    digitCount: "3",
  },
  {
    name: "Guyana",
    dial_code: "595",
    code: "GY",
    digitCount: "3",
  },
  {
    name: "Haiti",
    dial_code: "509",
    code: "HT",
    digitCount: "3",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "379",
    code: "VA",
    digitCount: "3",
  },
  {
    name: "Honduras",
    dial_code: "504",
    code: "HN",
    digitCount: "3",
  },
  {
    name: "Hong Kong",
    dial_code: "852",
    code: "HK",
    digitCount: "3",
  },
  {
    name: "Hungary",
    dial_code: "36",
    code: "HU",
    digitCount: "2",
  },
  {
    name: "Iceland",
    dial_code: "354",
    code: "IS",
    digitCount: "3",
  },
  {
    name: "India",
    dial_code: "91",
    code: "IN",
    digitCount: "2",
  },
  {
    name: "Indonesia",
    dial_code: "62",
    code: "ID",
    digitCount: "2",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "98",
    code: "IR",
    digitCount: "2",
  },
  {
    name: "Iraq",
    dial_code: "964",
    code: "IQ",
    digitCount: "3",
  },
  {
    name: "Ireland",
    dial_code: "353",
    code: "IE",
    digitCount: "3",
  },
  {
    name: "Isle of Man",
    dial_code: "44",
    code: "IM",
    digitCount: "2",
  },
  {
    name: "Israel",
    dial_code: "972",
    code: "IL",
    digitCount: "3",
  },
  {
    name: "Italy",
    dial_code: "39",
    code: "IT",
    digitCount: "2",
  },
  {
    name: "Jamaica",
    dial_code: "1876",
    code: "JM",
    digitCount: "4",
  },
  {
    name: "Japan",
    dial_code: "81",
    code: "JP",
    digitCount: "2",
  },
  {
    name: "Jersey",
    dial_code: "44",
    code: "JE",
    digitCount: "2",
  },
  {
    name: "Jordan",
    dial_code: "962",
    code: "JO",
    digitCount: "3",
  },
  {
    name: "Kazakhstan",
    dial_code: "77",
    code: "KZ",
    digitCount: "2",
  },
  {
    name: "Kenya",
    dial_code: "254",
    code: "KE",
    digitCount: "3",
  },
  {
    name: "Kiribati",
    dial_code: "686",
    code: "KI",
    digitCount: "3",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "850",
    code: "KP",
    digitCount: "3",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "82",
    code: "KR",
    digitCount: "2",
  },
  {
    name: "Kuwait",
    dial_code: "965",
    code: "KW",
    digitCount: "3",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "996",
    code: "KG",
    digitCount: "3",
  },
  {
    name: "Laos",
    dial_code: "856",
    code: "LA",
    digitCount: "3",
  },
  {
    name: "Latvia",
    dial_code: "371",
    code: "LV",
    digitCount: "3",
  },
  {
    name: "Lebanon",
    dial_code: "961",
    code: "LB",
    digitCount: "3",
  },
  {
    name: "Lesotho",
    dial_code: "266",
    code: "LS",
    digitCount: "3",
  },
  {
    name: "Liberia",
    dial_code: "231",
    code: "LR",
    digitCount: "3",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "218",
    code: "LY",
    digitCount: "3",
  },
  {
    name: "Liechtenstein",
    dial_code: "423",
    code: "LI",
    digitCount: "3",
  },
  {
    name: "Lithuania",
    dial_code: "370",
    code: "LT",
    digitCount: "3",
  },
  {
    name: "Luxembourg",
    dial_code: "352",
    code: "LU",
    digitCount: "3",
  },
  {
    name: "Macao",
    dial_code: "853",
    code: "MO",
    digitCount: "3",
  },
  {
    name: "Macedonia",
    dial_code: "389",
    code: "MK",
    digitCount: "3",
  },
  {
    name: "Madagascar",
    dial_code: "261",
    code: "MG",
    digitCount: "3",
  },
  {
    name: "Malawi",
    dial_code: "265",
    code: "MW",
    digitCount: "3",
  },
  {
    name: "Malaysia",
    dial_code: "60",
    code: "MY",
    digitCount: "2",
  },
  {
    name: "Maldives",
    dial_code: "960",
    code: "MV",
    digitCount: "3",
  },
  {
    name: "Mali",
    dial_code: "223",
    code: "ML",
    digitCount: "3",
  },
  {
    name: "Malta",
    dial_code: "356",
    code: "MT",
    digitCount: "3",
  },
  {
    name: "Marshall Islands",
    dial_code: "692",
    code: "MH",
    digitCount: "3",
  },
  {
    name: "Martinique",
    dial_code: "596",
    code: "MQ",
    digitCount: "3",
  },
  {
    name: "Mauritania",
    dial_code: "222",
    code: "MR",
    digitCount: "3",
  },
  {
    name: "Mauritius",
    dial_code: "230",
    code: "MU",
    digitCount: "3",
  },
  {
    name: "Mayotte",
    dial_code: "262",
    code: "YT",
    digitCount: "3",
  },
  {
    name: "Mexico",
    dial_code: "52",
    code: "MX",
    digitCount: "2",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "691",
    code: "FM",
    digitCount: "3",
  },
  {
    name: "Moldova",
    dial_code: "373",
    code: "MD",
    digitCount: "3",
  },
  {
    name: "Monaco",
    dial_code: "377",
    code: "MC",
    digitCount: "3",
  },
  {
    name: "Mongolia",
    dial_code: "976",
    code: "MN",
    digitCount: "3",
  },
  {
    name: "Montenegro",
    dial_code: "382",
    code: "ME",
    digitCount: "3",
  },
  {
    name: "Montserrat",
    dial_code: "1664",
    code: "MS",
    digitCount: "4",
  },
  {
    name: "Morocco",
    dial_code: "212",
    code: "MA",
    digitCount: "3",
  },
  {
    name: "Mozambique",
    dial_code: "258",
    code: "MZ",
    digitCount: "3",
  },
  {
    name: "Myanmar",
    dial_code: "95",
    code: "MM",
    digitCount: "2",
  },
  {
    name: "Namibia",
    dial_code: "264",
    code: "NA",
    digitCount: "3",
  },
  {
    name: "Nauru",
    dial_code: "674",
    code: "NR",
    digitCount: "3",
  },
  {
    name: "Nepal",
    dial_code: "977",
    code: "NP",
    digitCount: "3",
  },
  {
    name: "Netherlands",
    dial_code: "31",
    code: "NL",
    digitCount: "2",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "599",
    code: "AN",
    digitCount: "3",
  },
  {
    name: "New Caledonia",
    dial_code: "687",
    code: "NC",
    digitCount: "3",
  },
  {
    name: "New Zealand",
    dial_code: "64",
    code: "NZ",
    digitCount: "2",
  },
  {
    name: "Nicaragua",
    dial_code: "505",
    code: "NI",
    digitCount: "3",
  },
  {
    name: "Niger",
    dial_code: "227",
    code: "NE",
    digitCount: "3",
  },
  {
    name: "Nigeria",
    dial_code: "234",
    code: "NG",
    digitCount: "3",
  },
  {
    name: "Niue",
    dial_code: "683",
    code: "NU",
    digitCount: "3",
  },
  {
    name: "Norfolk Island",
    dial_code: "672",
    code: "NF",
    digitCount: "3",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "1670",
    code: "MP",
    digitCount: "4",
  },
  {
    name: "Norway",
    dial_code: "47",
    code: "NO",
    digitCount: "2",
  },
  {
    name: "Oman",
    dial_code: "968",
    code: "OM",
    digitCount: "3",
  },
  {
    name: "Pakistan",
    dial_code: "92",
    code: "PK",
    digitCount: "2",
  },
  {
    name: "Palau",
    dial_code: "680",
    code: "PW",
    digitCount: "3",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "970",
    code: "PS",
    digitCount: "3",
  },
  {
    name: "Panama",
    dial_code: "507",
    code: "PA",
    digitCount: "3",
  },
  {
    name: "Papua New Guinea",
    dial_code: "675",
    code: "PG",
    digitCount: "3",
  },
  {
    name: "Paraguay",
    dial_code: "595",
    code: "PY",
    digitCount: "3",
  },
  {
    name: "Peru",
    dial_code: "51",
    code: "PE",
    digitCount: "2",
  },
  {
    name: "Philippines",
    dial_code: "63",
    code: "PH",
    digitCount: "2",
  },
  {
    name: "Pitcairn",
    dial_code: "872",
    code: "PN",
    digitCount: "3",
  },
  {
    name: "Poland",
    dial_code: "48",
    code: "PL",
    digitCount: "2",
  },
  {
    name: "Portugal",
    dial_code: "351",
    code: "PT",
    digitCount: "3",
  },
  {
    name: "Puerto Rico",
    dial_code: "1939",
    code: "PR",
    digitCount: "4",
  },
  {
    name: "Qatar",
    dial_code: "974",
    code: "QA",
    digitCount: "3",
  },
  {
    name: "Romania",
    dial_code: "40",
    code: "RO",
    digitCount: "2",
  },
  {
    name: "Russia",
    dial_code: "7",
    code: "RU",
    digitCount: "1",
  },
  {
    name: "Rwanda",
    dial_code: "250",
    code: "RW",
    digitCount: "3",
  },
  {
    name: "Reunion",
    dial_code: "262",
    code: "RE",
    digitCount: "3",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "590",
    code: "BL",
    digitCount: "3",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "290",
    code: "SH",
    digitCount: "3",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "1869",
    code: "KN",
    digitCount: "4",
  },
  {
    name: "Saint Lucia",
    dial_code: "1758",
    code: "LC",
    digitCount: "4",
  },
  {
    name: "Saint Martin",
    dial_code: "590",
    code: "MF",
    digitCount: "3",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "508",
    code: "PM",
    digitCount: "3",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "1784",
    code: "VC",
    digitCount: "4",
  },
  {
    name: "Samoa",
    dial_code: "685",
    code: "WS",
    digitCount: "3",
  },
  {
    name: "San Marino",
    dial_code: "378",
    code: "SM",
    digitCount: "3",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "239",
    code: "ST",
    digitCount: "3",
  },
  {
    name: "Saudi Arabia",
    dial_code: "966",
    code: "SA",
    digitCount: "3",
  },
  {
    name: "Senegal",
    dial_code: "221",
    code: "SN",
    digitCount: "3",
  },
  {
    name: "Serbia",
    dial_code: "381",
    code: "RS",
    digitCount: "3",
  },
  {
    name: "Seychelles",
    dial_code: "248",
    code: "SC",
    digitCount: "3",
  },
  {
    name: "Sierra Leone",
    dial_code: "232",
    code: "SL",
    digitCount: "3",
  },
  {
    name: "Singapore",
    dial_code: "65",
    code: "SG",
    digitCount: "2",
  },
  {
    name: "Slovakia",
    dial_code: "421",
    code: "SK",
    digitCount: "3",
  },
  {
    name: "Slovenia",
    dial_code: "386",
    code: "SI",
    digitCount: "3",
  },
  {
    name: "Solomon Islands",
    dial_code: "677",
    code: "SB",
    digitCount: "3",
  },
  {
    name: "Somalia",
    dial_code: "252",
    code: "SO",
    digitCount: "3",
  },
  {
    name: "South Africa",
    dial_code: "27",
    code: "ZA",
    digitCount: "2",
  },
  {
    name: "South Sudan",
    dial_code: "211",
    code: "SS",
    digitCount: "3",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "500",
    code: "GS",
    digitCount: "3",
  },
  {
    name: "Spain",
    dial_code: "34",
    code: "ES",
    digitCount: "2",
  },
  {
    name: "Sri Lanka",
    dial_code: "94",
    code: "LK",
    digitCount: "2",
  },
  {
    name: "Sudan",
    dial_code: "249",
    code: "SD",
    digitCount: "3",
  },
  {
    name: "Suriname",
    dial_code: "597",
    code: "SR",
    digitCount: "3",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "47",
    code: "SJ",
    digitCount: "2",
  },
  {
    name: "Swaziland",
    dial_code: "268",
    code: "SZ",
    digitCount: "3",
  },
  {
    name: "Sweden",
    dial_code: "46",
    code: "SE",
    digitCount: "2",
  },
  {
    name: "Switzerland",
    dial_code: "41",
    code: "CH",
    digitCount: "2",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "963",
    code: "SY",
    digitCount: "3",
  },
  {
    name: "Taiwan",
    dial_code: "886",
    code: "TW",
    digitCount: "3",
  },
  {
    name: "Tajikistan",
    dial_code: "992",
    code: "TJ",
    digitCount: "3",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "255",
    code: "TZ",
    digitCount: "3",
  },
  {
    name: "Thailand",
    dial_code: "66",
    code: "TH",
    digitCount: "2",
  },
  {
    name: "Timor-Leste",
    dial_code: "670",
    code: "TL",
    digitCount: "3",
  },
  {
    name: "Togo",
    dial_code: "228",
    code: "TG",
    digitCount: "3",
  },
  {
    name: "Tokelau",
    dial_code: "690",
    code: "TK",
    digitCount: "3",
  },
  {
    name: "Tonga",
    dial_code: "676",
    code: "TO",
    digitCount: "3",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "1868",
    code: "TT",
    digitCount: "4",
  },
  {
    name: "Tunisia",
    dial_code: "216",
    code: "TN",
    digitCount: "3",
  },
  {
    name: "Turkey",
    dial_code: "90",
    code: "TR",
    digitCount: "2",
  },
  {
    name: "Turkmenistan",
    dial_code: "993",
    code: "TM",
    digitCount: "3",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "1649",
    code: "TC",
    digitCount: "4",
  },
  {
    name: "Tuvalu",
    dial_code: "688",
    code: "TV",
    digitCount: "3",
  },
  {
    name: "Uganda",
    dial_code: "256",
    code: "UG",
    digitCount: "3",
  },
  {
    name: "Ukraine",
    dial_code: "380",
    code: "UA",
    digitCount: "3",
  },
  {
    name: "United Arab Emirates",
    dial_code: "971",
    code: "AE",
    digitCount: "3",
  },
  {
    name: "United Kingdom",
    dial_code: "44",
    code: "GB",
    digitCount: "2",
  },
  {
    name: "United States",
    dial_code: "1",
    code: "US",
    digitCount: "1",
  },
  {
    name: "Uruguay",
    dial_code: "598",
    code: "UY",
    digitCount: "3",
  },
  {
    name: "Uzbekistan",
    dial_code: "998",
    code: "UZ",
    digitCount: "3",
  },
  {
    name: "Vanuatu",
    dial_code: "678",
    code: "VU",
    digitCount: "3",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "58",
    code: "VE",
    digitCount: "2",
  },
  {
    name: "Vietnam",
    dial_code: "84",
    code: "VN",
    digitCount: "2",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "1284",
    code: "VG",
    digitCount: "4",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "1340",
    code: "VI",
    digitCount: "4",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "681",
    code: "WF",
    digitCount: "3",
  },
  {
    name: "Yemen",
    dial_code: "967",
    code: "YE",
    digitCount: "3",
  },
  {
    name: "Zambia",
    dial_code: "260",
    code: "ZM",
    digitCount: "3",
  },
  {
    name: "Zimbabwe",
    dial_code: "263",
    code: "ZW",
    digitCount: "3",
  },
];

const handleInput = (e, c_arr) => {
  if (!e) return false;
  
  let country = c_arr.find((c) => c.dial_code == e.slice(0, c.digitCount));
  console.log(country);
  if (!country) return false
  let code = country?.dial_code;
  if (e.split(code)[1] == "") {
    
    return false;
  }
  // console.log(e.split(code)[1])
  return true;
};
const token = localStorage.getItem("token");

const HEADERS_LOGIN = {
  "Content-Type": "application/json",
  "Accept": "application/json",
  "X-Content-Type-Options": "nosniff",
  "Strict-Transport-Security": "max-age=max-age=63072000;includeSubDomains; preload",
  "X-Frame-Options": "SAMEORIGIN",
  "X-XSS-Protection": 1,
}

const HEADERS = {
  "Content-Type": "application/json",
  Accept: "application/json",
  Authorization: `Bearer ${token}`,
}
const SECURITY_HEADERS = {
  "X-Content-Type-Options": "nosniff",
  "Strict-Transport-Security": "max-age=max-age=63072000;includeSubDomains; preload",
  "X-Frame-Options": "SAMEORIGIN",
  "X-XSS-Protection": 1,
}

const URL = {
  AboutWadiaa: "https://wadiaa.com/about/",
  TheTeam: "https://wadiaa.com/about/#aboutteam",
  ContactUs: "https://wadiaa.com/contact/",
  Press: "https://wadiaa.com/press-media/",
  Careers: "https://wadiaa.com/careers/",
  WhyInvest: "https://wadiaa.com/investing-faq/",
  HowtoInvest: "https://wadiaa.com/how-to-invest/",
  InvestorFeedback: "https://wadiaa.com/investor-feedback/",
  WhyRaisefunds: "https://wadiaa.com/fundraising-faq/",
  HowtoRaiseFunds: "https://wadiaa.com/how-to-raise-funds/",
  TermsofUse: "https://wadiaa.com/terms-of-use/",
  RisksDisclaimer: "https://wadiaa.com/risks/",
  PrivacyPolicy: "https://wadiaa.com/policies/",
  Learn: "https://wadiaa.com/learn/",
  TermsOfUse: "https://wadiaa.com/terms-of-use/"
}

const SOCIALURL = {
  LinkedIn: "https://www.linkedin.com/company/alwadiaa/",
  Instagram: "https://www.instagram.com/wadiaafunding/",
  Twitter: "https://twitter.com/wadiaafunding",
  Facebook: "https://www.facebook.com/wadiaafunding",
  YouTube: "https://www.youtube.com/@wadiaa"
}


let WhiteColor = [
  ROUTES.RAISEMONEY.COMPANY_DETAILS,
  ROUTES.RAISEMONEY.CAMPAIGN,
  ROUTES.RAISEMONEY.PRE_SCREENING,
  ROUTES.INVEST.TERMS_CONDITION,
  ROUTES.INVESTMENT.INDIVIDUAl_ACCREDITATION,
  ROUTES.INVESTMENT.LEGAL_ACCREDITATION,
  ROUTES.INVESTMENT.INVESTMENT,
  ROUTES.DASHBOARD,
  ROUTES.PROFILE_PAGE,
  ROUTES.RAISEDASHBOARD,
  ROUTES.NOTIFICATION,
  ROUTES.CONTACT,
  ROUTES.PAYMENUAL
];

let BlueColor = [
  ROUTES.OTP,
  ROUTES.INVEST_HOME,
  ROUTES.RAISEMONEY.REQUEST,
  ROUTES.INVEST.INVEST,
  ROUTES.INVEST.INDIVIDUAL,
  ROUTES.INVEST.BUSINESS,
  ROUTES.PAYDETAILS,
  ROUTES.PAYHISTORY,
  ROUTES.PAYINITIATE,
  ROUTES.PAYSUCCESS,
  ROUTES.PAYFAILURE,
  ROUTES.LEARN,
  ROUTES.FORGORPASSWORD,
  ROUTES.RESETPASSWORD
];

let BlackColor = [
  ROUTES.HOME,
  ROUTES.SIGN_UP,
  ROUTES.LOGIN,
  ROUTES.RAISE_HOME
]


const COMMON = {
  COUNTRIES,
  TODAYDATE,
  COMPANYTYPE,
  SECTOR,
  CURRENCY,
  arrayOfCountries,
  handleInput,
  HEADERS_LOGIN,
  HEADERS,
  URL,
  SECURITY_HEADERS,
  SOCIALURL,
  WhiteColor,
  BlueColor,
  BlackColor
};

export default COMMON;
