export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const PRESCREENING_STATUS = "PRESCREENING_STATUS";
export const PRESCREENING_CONTENT = "PRESCREENING_CONTENT";
export const USER_TYPE = "USER_TYPE";

//for campaign

export const CAMPAIGN_CONTENT = "CAMPAIGN_CONTENT";
export const CAMPAIGN_ID = "CAMPAIGN_ID";
export const DECODE = "DECODE";
export const CAMPIAGN_SINGLEDATA = "CAMPIAGN_SINGLEDATA";

// for investor

export const INVESTOR_CONTENT = "INVESTOR_CONTENT";
export const INVESTOR_TYPE = "INVESTOR_TYPE";


